# Generated by Django 6.1.1 on 2026-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(null=True),
        ),
    ]
