# Generated by Django 5.1.3 on 2024-11-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restmain', '0001_initial'),
        ('users', '0002_alter_user_email_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateField()),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restmain.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
