# Generated by Django 6.1.1 on 2026-09-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0004_appointment_payment_ref_appointment_service_id_and_more",
        ),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user_id",
        ),
        migrations.AddField(
            model_name="review",
            name="appointment_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointments.appointment",
            ),
            preserve_default=False,
        ),
    ]
