# Generated by Django 6.1.1 on 2026-10-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_remove_review_user_id_review_appointment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="treatment_type",
        ),
    ]
