# Generated by Django 5.1.3 on 2024-11-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('card_code', models.TextField(max_length=16, primary_key=True, serialize=False)),
                ('remaining_value', models.FloatField()),
                ('purchased_on', models.DateField()),
                ('valid_until', models.DateField()),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
