# Generated by Django 4.0.4 on 2022-05-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=2000)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ImageURL', models.URLField()),
            ],
        ),
    ]
