# Generated by Django 4.0.4 on 2022-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_wide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='BookingLink',
            field=models.CharField(default='/', max_length=100),
            preserve_default=False,
        ),
    ]
