# Generated by Django 4.0.4 on 2022-05-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_wide', '0002_service_bookinglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='BookingLink',
        ),
    ]
