# Generated by Django 6.1.1 on 2026-09-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_appointment_id"),
        ("restmain", "0002_service_exclusive"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_ref",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restmain.service",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "CONFIRMED"),
                    ("RESERVED", "RESERVED"),
                    ("AVAILABLE", "AVAILABLE"),
                ],
                default="AVAILABLE",
            ),
        ),
    ]
