# Generated by Django 6.1.1 on 2026-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restmain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="exclusive",
            field=models.BooleanField(default=False),
        ),
    ]
